### ISSUE TITLE
Patcher9x fails to patch Windows 98 on QEMU, resulting in fatal error with no information about it on the internet

### ISSUE THREAD

**Issue by TheSystemGuy1337** [JHRobotics/patcher9x#12]
Found out the hard way. Patcher9x doesn't do anything, and Windows 98 tosses "msgsrv32 caused an invalid page fault in module <unknown> at 0000:00006009" and then OOBE quits. All I know is TLB invalidation is still being triggered here, and patcher9x says the patch was successful

**Comment by JeremyStarTM** [comment]
Are you running Windows 98 FE? Because on my Arch Linux QEMU + KVM setup patcher9x successfully patches Windows 98 SE.

**Comment by TheSystemGuy1337** [comment]
I was using SE the whole time On Apr 7, 2023, at 1:59 PM, JeremyStarTM ***@***.***> wrote:﻿
Are you running Windows 98 FE? Because on my Arch Linux QEMU + KVM setup patcher9x successfully patches Windows 98 SE.

**Comment by JeremyStarTM** [comment]
Hmm that's weird. Are you using a different language of some kind? I've heard that (for example) Russian Windows is slightly different then the English one. I'm using a German iso and it worked.

**Comment by TheSystemGuy1337** [comment]
I’m using standard en_us Windows 98 (English, United States). I only encounter this issue on ChromeOS’s shite Linux emulation On Apr 7, 2023, at 4:38 PM, JeremyStarTM ***@***.***> wrote:﻿
Hmm that's weird. Are you using a different language of some kind? I've heard that (for example) Russian Windows is slightly different then the English one. I'm using a German iso and it worked.

**Comment by JeremyStarTM** [comment]
Maybe ChromeOS isn't the best virtualization host. Could you try using patcher9x in a VM on Windows/Linux/macOS?

**Comment by TheSystemGuy1337** [comment]
Had same issue on Windows 11 Pro on a AMD Ryzen. It’s what I tried it on and it catastrophically failedOn Apr 8, 2023, at 7:09 AM, JeremyStarTM ***@***.***> wrote:﻿
Maybe ChromeOS isn't the best virtualization host. Could you try using patcher9x in a VM on Windows/Linux/macOS?

**Comment by JeremyStarTM** [comment]
Weird. I don't know what your problem is anymore... and sorry for not reponding in a while, I'm very busy at the moment.

**Comment by TheSystemGuy1337** [comment]
I forgot this issue still existed. I have **given up**, moved on and forgot about it. I at one point attempted to hack Ubuntu on to that **borderline netbook** running proprietary Linux but was unable to due to Google using a proprietary bootstrap EEPROM. It was $20 and was unsupported, so I tossed the Chromebook in the trash (where it belongs). Any point or purpose of this issue has all but evaporated, so I'm shutting it down. It is now safe to turn off your computer.
