### ISSUE TITLE
FIX95CPU_V3_FINAL doesn't run on Windows 98

### ISSUE THREAD

**Issue by Torinde** [JHRobotics/patcher9x#2]
Thank you for the patch!

I see you plan to add the FIX95CPU_V3_FINAL (whose automatic installer doesn't run on Win98 First Edition - but I got the NDIS Windows Protection Error, so it's needed) and 48-bit LBA patches as well. 
Would be nice to have also the 4GB RAM and >1TB partition - also from [Rudolph Loew](http://lonecrusader.x10host.com/rloew/rloew.html)

Or maybe the WinME 2GB RAM fix in SYSTEM.INI [386Enh] MaxPhysPage=7C6FF

On Win95 RTM - FIX95CPU_V3_FINAL makes 3 extra floppy drives to appear, I assume that comes from one of the integrated patches. Would be nice if you can make these superfluous drives optional in your package.

**Comment by JHRobotics** [comment]
Hello @Torinde,

Yes, I know it - FIX95CPU_V3_FINAL only replacing Windows 95 files, so is not compatible with any other system – there is more generic way to patch files (https://www.betaarchive.com/forum/viewtopic.php?t=29224), but I didn’t look deeply on it to test if the problematic code is in W95 and W98 FE same. There is maybe another problem – I did some tests on AMD Ryzen and Windows 95 fail with system protection error even with this patch applied. So maybe the fixure isn’t enough (or there is another bug). 

I’m sorry to disappoint you, but I don’t plain to integrate any feature update – for example 4G patch applying some memory splitting/switching (from brief view) and it could bring some new compatibility issues. This is problem for all 9X systems – if you are applying more and more updates the system will be more and more unstable. But on other hand, I will try make my patch compatible with these updates.

I remember than on real hardware if I changed GPU more times (of course different vendors and different drivers) the system after a few these changes was dead. When 9X where primary system, every year was necessary to reinstall system – with installing more and more software the system was slower and slower (sometime unstable too) so after about year it was unbearable.

I hope you understand that I’m trying to apply as less changes as it’s possible only to brings the OS to live – and if you will need other patches/updates/drivers you can install them separately.

**Comment by Torinde** [comment]
Thanks, understood.
Win98RTM - installs in Virtualbox without FIX95CPU via:
- using old PC, VBox 6.0.x, no VT-x/AMD-V on host (and no nested pages). Then install [NDIS fix](https://www.betaarchive.com/forum/viewtopic.php?t=24439) - [312108USA8.EXE](http://www.autourdupc.com/Logiciel/WIN98/Softs/98/312108USA8.EXE) from inside Windows. Then your patch. Then use the same virtual machine on a Ryzen PC with VBox 6.1.x, enable nested pages for the host (and that it seems enables also VT-x/AMD-V on host), then it works.

Win95RTM 
- in addition to FIX95CPU, it needs that [VT-x/AMD-V is not utilized on the host](https://forums.virtualbox.org/viewtopic.php?t=96262). So, again, because VBox 6.1.x doesn't have a checkbox to disable that?? - use VBox 6.0.x first (and then be careful to not do any adjustments of Virtual machine settings on 6.1.x because it seems that enables VT-x/AMD-V on the host), then use on Ryzen PC/VBox 6.1.x.

It would be very nice if your patch can somehow take care of those issues - without the need to use old PC and/or old VBox version.

**Comment by JHRobotics** [comment]
Hello @Torinde,

I made a new release of my patcher, now with CPU speed limit bug fix included. So, you should now run 95/98 FE without turning HW virtualization off. I try even installed and run Memphis 4.10.1351 and with patch is stable even on AMD Ryzen/11gen Intel (OK - you must set virtual machine time to back 1997 and during installation is BSOD related to ACPI, but it works!).

For Win 95, it is better to patch the installation media, or you will need to install the patch twice - after the first reboot and again after the installation of the net.

BTW: VirtualBox 6.1 can't run virtual machine without VT-x/AMD-V because dynamic recompiler (internally called REM) was kicked out from the code. There is alternative called IEM (`VBoxManage setextradata "vm-name" VBoxInternal/EM/IemExecutesAll 1`) which is classical emulator (like DosBox with CPU in normal mode) but is not very stable.

**Comment by Torinde** [comment]
Great work, thank you!

**Comment by Torinde** [comment]
> There is alternative called IEM (VBoxManage setextradata "vm-name" VBoxInternal/EM/IemExecutesAll 1) which is **classical emulator** (like DosBox with CPU in normal mode)

That may come in handy in the future for [x86-S](https://en.wikipedia.org/wiki/X86-64#x86-S) CPUs that lack 32-bit OS support. But I wonder why VirtualBox is not using the same when running on Apple silicon to run Windows x64 guests... is it _so_ unstable/slow...
