### ISSUE TITLE
“Wrong/unknown format format” when using the DOS tool

### ISSUE THREAD

**Issue by TheMiningTeamYT** [JHRobotics/patcher9x#8]
I was attempting to patch my own 98 machine using the DOS tool, but this error kept coming up:
“Error: wrong/unknown format format
 (trace: exact.c on 299)”
The command I was running was “patch9x C:\windows\system -wx-extract -patch-tlb -o C:\windows\system\vmm32\vmm.vxd”

**Comment by JHRobotics** [comment]
Hi, please use last release. I removed this "mode", because was confusing and don't working in all cases. In new version you can do it by this:
`patch9x --patch-tlb C:\windows\system\vmm32\vmm.vxd`
